### PR TITLE
2 implement lookup 3

### PR DESCRIPTION
**Pull request by zancas**
OK, here's a new branch with a total of 8 commits.

All of the original commits (development history, warts, etc.) are still available on 2_implement_lookup_2.

We can continue to iterate on this process until we finally have a nice "story-telling" set of commits that make it easy for someone following the development of the code-base to learn how things were built.

Or maybe this branch will be good enough.   At any rate, we've got the complete (true) history, and a revised version that makes for easier reading to merge into production.

Looking forward to your review comments, and further iterations of improvement.

### CODE REVIEW

**Comment by taoeffect** [comment]
@dionyziz feel free to comment. The code seems like it should work. There's the issue of it not using HTTPS atm, but that will be fixed in a separate PR.

Looks good I think. How do I run and test this btw? (Python newb here).

If it runs and tests work I'll merge it! Great job! :+1:

**Comment by dionyziz** [comment]
Small comments on git: 
1. You don't need to open a new pull request after you rewrite history; just push force to the old branch you used for your PR. That way, we can keep track of reviews and whether issues have been addressed. 
2. You can PR from a branch in your personal GitHub fork. That way, we'll keep the upstream repo branches clean (it should just have master I think)

That's the way we work in OpenBazaar and it seems to be working well for us.

**Comment by dionyziz** [comment]
Also, regarding your comments on #7, what you're proposing may work for shared branches, but these are rarely needed. What we do is we make the author developer of a PR own that PR and other devs can review it to recommend changes. That developer is the responsible for merging it and the only one adding code there. If someone else really _must_ add code there, they can PR on the PR.

This works for most code changes that are not complete rewrites or huge features.

**Comment by taoeffect** [comment]
I tested this and it seems to work. Anything that needs fixing can be done in a separate PR.

Great job @zancas! Merging.

**Pull request merged**
