### PR TITLE
[WIP]Added a test for a complete request/response,Issue #13

### PR DESCRIPTION
**Pull request by charapod**
Hello! 

We tried to write a test for Issue #13 ( @dionyziz ). Previous tests mocked: 
'dnschain.server.urllib.FancyURLopener'
which was not imported in dnschain.server, so they failed. For that, we changed "urllib.FancyURLopener" to "urllib2.urlopen", which is what dnschain.server uses. 

If you do not agree with this change, let us know, so as to revert it :) . 

Let us know if there is anything you want us to change or add.

### CODE REVIEW

**Comment by dionyziz** [comment]
@greg do you plan to add travis support during your hackathon this weekend? That way we could automate running these tests before we merge them.

**Comment by taoeffect** [comment]
@dionyziz I'll try to fit it in, I've never done it before so I don't know how long it will take. Any tips/starting points appreciated!

**Comment by dionyziz** [comment]
Should take less than 30 minutes to set up. Read the docs on travis-ci.org, write a travis.yml file and you should be got to go! Feel free to ping me for questions.

**Comment by dionyziz** [comment]
@charapod Congratulations on your first merge! Have a beer on us. @changetip

**Comment by changetip** [comment]
Hi charapod, dionyziz sent you a Bitcoin tip worth a beer (8,753 bits/$3.50), and I'm here to deliver it ➔ **[collect your tip at ChangeTip.com](https://www.changetip.com/collect/131934)**.

**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by charapod** [comment]
hehe! Thanks @dionyziz! Moving on :)

**Comment by jackjohns** [comment]
@dionyziz give me beer too plz :P

**Comment by dionyziz** [comment]
Sure, @jackjohns, how does this issue look to you? :)

https://github.com/OpenBazaar/OpenBazaar/issues/487

**Pull request merged**
